version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - PYTHONPATH=/app
    
  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000